# 아이템 7 : 결과 부족이 발생할 경우 null과 Failure를 사용하라

함수가 원하는 결과를 만들어 낼 수 없을 때가 있다.

- 서버로부터 데이터를 읽어오는데, 인터넷 연결 문제가 있는 경우
- 조건에 맞는 첫 번째 요소를 찾으려 했는데, 맞는 요소가 없는 경우

이러한 상황을 처리하는 메커니즘은 크게 두 가지가 있다.

1. null 또는 실패를 나타내는 sealed 클래스 리턴
2. 예외 throw

위 두 방법은 차이점이 있다.

- 예외는 정보를 전달하는 방법으로 사용해선 안된다. 예외는 잘못된 특별항 상황을 나타내야 하며, 처리되어야 한다.
- 예외는 예외적인 상황이 발생했을 때 사용하는 것이 좋다.

이런 이유를 정리하자면 다음과 같다.

- 많은 개발자가 예외가 전파되는 과정을 제대로 추적하지 못한다.
- 코틀린의 모든 예외는 unchecked예외이다.
    - 처리하지 않아도 실행에 문제가 없는 예외.
    - 반드시 처리하게 강제되는 예외는 checked예외이다.
- 예외는 예외적인 상화을 처리하기 위해 만들어졌으므로, 명시적인 테스트 만큼 빠르게 동작하지 않는다.
- try-catch 블록 내부에 코드를 배치하면, 컴파일러가 할 수 있는 최적화가 제한된다.

첫 번째로 작성한 null과 Failure는 예상되는 오류를 표현할 때 굉장히 좋다. 명시적이고, 효율적이며 간단한 방법으로 처리가 가능하다.

```kotlin
예측할 수 있는 범위의 오류는 null과 Failure를 사용하고, 예측하기 어려운 예외적인 범위의 오류
예외를 throw해서 처리하는 것이 좋다.
```

```kotlin
sealed class Result<out T> {
    class Success<out T>(val result: T) : Result<T>()
    class Failure(val throwable: Throwable) : Result<Nothing>()
}

class JsonParsingException : Exception()

// null을 사용하는 경우
inline fun <reified T> String.readObjectOrNull(): T? {
    // ..
    if(incorrectSign) {
        return null
    }
}

// Failure(sealed class)사용하는 경우
inline fun <reified T> String.readObject : Result<T> {
    // ..
    if(incorrectSign) return Failure(JsonParsingException())
    // ..
    return Success(result)
}
```

- 이렇게 표시되는 오류는 다루기 쉬우며, 놓치기 어렵다.
- null을 처리해야 한다면 safe call or Elvis 연산자 같은 다양한 널안전성 기능을 활용하자.

### 요약

- 이러한 오류 처리 방식은 try-catch 블록 보다 효율적이다. 사용하기도 쉽고 더 명확하다.
- null값과 sealed result 클래스는 명시적으로 처리해야하고, 애플리케이션 흐름을 중지하지도 않는다.
- null값과 sealed result 클래스의 차이점은 추가적인 정보 전달은 sealed result, 그렇지 않으면 null
    - Failure를 처리할 땐 필요한 정보를 가질 수 있다.
- 예상되는 오류는 null과 Failure, 안된다면 예외를 throw하자.
- nullable을 리턴하지말고 무엇이 리턴되는지 예측할 수 있게 하는것이 좋다.
